config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#show', page: 'home'
  get '/pages/:page', to: 'pages#show'
  
  resources :movies
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/profile/edit', to: 'users#edit'
  patch '/profile', to: 'users#update'
  get "/profile/movies", to: "users#movies", as: "profile_movies"
  post "/profile/issues/:id", to: "users#addissue", as: "addissue"
  delete "/profile/issues/:id", to: "users#removeissue", as: "removeissue"

  get '/login', to: 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_and_belongs_to_many :movies
    has_and_belongs_to_many :users
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/genre_user.rb
class GenreUser < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/models/issue.rb
class Issue < ApplicationRecord
    has_and_belongs_to_many :movies
    has_and_belongs_to_many :users
end

app/models/issue_movie.rb
class IssueMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :issue
end

app/models/issue_user.rb
class IssueUser < ApplicationRecord
  belongs_to :user
  belongs_to :issue
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_and_belongs_to_many :genres
    has_and_belongs_to_many :issues
    before_action :authorize

    def self.search(search)
        if search
            left_outer_joins(:issues).where(["lower(movies.title) LIKE ? OR lower(issues.keyword) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase]).distinct
        else
            all
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true
    has_and_belongs_to_many :genres
    has_and_belongs_to_many :issues
    has_many :movies, -> { distinct }, through: :issues

    def unassigned_issues
        issues = self.issues.select(:id)
        Issue.where("id NOT IN (?)", issues)
    end

    def dont_watch
        Movie.where("id NOT IN (?)", self.movies.to_a)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authorize
    
    def index
        @movies = Movie.search(params[:search])
    end

    def show
        @movie = Movie.find(params[:id])
    end

    private

    def movie_params
        params.require(:movie).permit(:title, :year, :run_time, :rating, :synopsis, :psychologist, :why_recommend, :learn)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def show 
        page = params[:page]
        render "pages/#{page}"
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to movies_path, notice: "Logged In!"
        else
            flash.now.alert = 'Invalid login credentials - try again!'
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to movies_path
    
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    redirect_to profile_edit_path
  end

  def addissue
    current_user.issues.push(Issue.find(params[:id]))
    redirect_to profile_edit_path
  end
  
  def removeissue
    current_user.issues.delete(params[:id])
    redirect_to profile_edit_path
  end

  def movies
    @movies = current_user.dont_watch
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Inlite", root_path, class: "navbar-brand" %>
        </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to "All Movies", movies_path %></li>
                <li><%= link_to "My Profile", profile_edit_path %></li>
                <li><%= link_to "My Movies", profile_movies_path %></li>
                Welcome, <%= current_user.name %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to 'Log Out', session_path('dummy'), method: :delete, class: "logout btn btn-default navbar-btn"%>
              <% else %>
                <%= link_to 'Log In', login_path, class: "login btn btn-default navbar-btn" %>
                &nbsp;|&nbsp;
                <%= link_to 'Sign Up', new_user_path, class: "signup btn btn-default navbar-btn" %>
              <% end %>
            </ul>
            <div class="navbar-form" role="search">
                <%= form_tag movies_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search] %>
                    <%= submit_tag "Search", name: nil, class: "search-button" %>
                <% end %>
            </div>
          </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inlite</title>
    <%= csrf_meta_tags %>

    <!-- jQuery below -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>

    <!-- Bootstrap below -->
     <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
     <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

    <!-- custom JS and CSS below -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    
    <%= render "layouts/header" %>

    <div class="container">
      <%= yield %>
    </div>

    

  </body>
</html>

app/views/movies/index.html.erb
<h1>Movie Recommendations</h1>
<hr>

<div class="row">   
    <% @movies.each do |movie| %>
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail il-thumbnail-image">
                <%= link_to (image_tag(movie.image_uri, alt: "Movie picture", class: "movie-image")), movie_path(movie) %>
            </div>
            <div>
                <h4><%= link_to movie.title, movie_path(movie) %></h4><br>
            </div>
        </div>
    <% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <h2>Movie Details</h2>
        <%= image_tag(@movie.image_uri, class: "dashboard-image") %>
            <div class="details">
                <h3><%= @movie.title %></h3>
                <p><%= @movie.year %> &nbsp;&nbsp;|&nbsp;&nbsp;<%= @movie.run_time %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= @movie.rating %>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <% @movie.genres.each do |genre| %>
                        <%= genre.keyword %> 
                    <% end %>
                </p>
                <div class="psychologist"><strong>Recommended by</strong><br><%= @movie.psychologist %></div><br>
            </div>
    </div>
</div>

<%= link_to "Back", movies_path, class: "btn btn-default" %>

app/views/pages/home.html.erb
<% if !current_user %>
    <div class="jumbotron">
        <h1><%= image_tag("https://i.imgur.com/98ZfXT5.png", alt: "inlite logo", class: "logo") %></h1>
        <hr>
        <h3>watch movies for GOOD</h3>
        <br>
        <p> A Combination of Cinema Therapy and CBT techniques, integrated in a Chatbot and developed with Therapists is innovative in the field. 
            Cinema Therapy is a technique that encourages viewers to discover their maladaptive beliefs, problematic thoughts, and feelings while discussing movie characters and stories. 
            Treatment begins with watching a movie and is followed by exercises and video tutorials with the chatbot to track and reflect movie's effect on the viewer.</p>
        <p><%= link_to "Sign Up Now", new_user_path, class: "call-to-action btn btn-default btn-lg" %></p>
    </div>
<% end %>

    <div class="movie-grid">
        <div class="row">   
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/d0SuuF9.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/HwNj0Cw.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>  
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/NQmDWGJ.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/SdUuZry.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/uvNNygx.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/9Y8BNke.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/uBY4iB3.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
            <div class="thumbnail il-thumbnail-image col-sm-6 col-md-3 col-centered">
                <%= image_tag("https://i.imgur.com/LrUbJSy.jpg", alt: "Movie picture", class: "movie-image") %>
            </div>
        </div>
    </div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h2><%= current_user.name %>'s Profile</h2>
<hr>
<h4>Update your profile</h4>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_for @user, url: profile_path do |f| %>

                <div class="field">
                <%= f.label :email, class: "label" %>
                <%= f.email_field :email, class: "text" %> 

                <%= f.submit "Save Changes", class: "save" %>
           <% end %>
<hr>

<p class="description">Click to choose from "All issues" to filter your movie recommendations</p>

<div class="issues1">
<h3>Your issues</h3>
    <div class="col-sx-4">
        <% current_user.issues.each do |issue| %>
            <%= link_to issue.keyword, removeissue_path(issue), method: :delete, class: "issue-have btn btn-info-outline" %>
        <% end %>
    </div>
</div>

<div class="issues2">
<h3>All issues</h3>
    <div class="col-sx-4">
        <% current_user.unassigned_issues.each do |issue| %>
            <%= link_to issue.keyword, addissue_path(issue), method: :post, class: "issue-not btn btn-info-outline" %>
        <% end %>
    </div>
</div>

app/views/users/movies.html.erb
<h1>My Movies</h1>

<% if current_user.movies.count > 0 %>

    <div class="row">   
        <% @movies.each do |movie| %>
            <div class="col-sm-6 col-md-3">
                <div class="thumbnail il-thumbnail-image">
                    <%= link_to (image_tag(movie.image_uri, alt: "Movie picture", class: "movie-image")), movie_path(movie) %>
                </div>
                <div>
                    <h4><%= link_to movie.title, movie_path(movie) %></h4><br>
                </div>
            </div>
        <% end %>
    </div>

<% else %>
    <h4>Go back and update your profile to see a list of therapeutic movies.</h4>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<hr>
<div class="container">
  <div class="col-md-4">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name, class: "text" %>
      </div>
      <div class="field">
        <%= f.label :email, class: "label" %>
        <%= f.text_field :email, class: "text" %>
      </div>
      <div class="field">
        <%= f.label :password, class: "label" %>
        <%= f.password_field :password, class: "text" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, class: "label" %>
        <%= f.password_field :password_confirmation, class: "text" %>
      </div>
      <div class="actions"><%= f.submit "Sign Up", class: "signup"%></div>
    <% end %>
  </div>
</div>